server:
  port: 8095

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  #### database ??
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jjang052
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  #update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: oracle
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect

  ######구글 로그인 정보 #######
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 160447529731-4q5hpngmudqtntjsdiltb9q7cvmka0f4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          github:
            client-id: 076098305e5006091a2f
            client-secret: 0cde5e233b09f1ea27d6e38d18102be1b487b235

          naver:
            client-id: AdrCYpBiExYeAhFzopVY
            client-secret: RwCRxuWcCU
            scope:
              - nickname
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8094/login/oauth2/code/naver

          kakao:
            client-id: 574849fde6e94807f7716aa6db5933bf
            client-secret: m7HGruKqluMMdoyKAfJPU4EMvX9uqOCc
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8094/login/oauth2/code/kakao
            client-authentication-method: client_secret_post




        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  mail:
    host: smtp.naver.com
    port: 465
    username: jjang051hta@naver.com
    password: asdf1234!!
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
    protocol: smtps



#### mybatis ??
#mybatis:
#  config-location: classpath:mapper/config/config.xml
#  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jjang051.board.dto  # comma

#### log ??  fatal > error > warn > info > debug
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 파라미터 보여준다.

file:
  path: C:/outstargram/

pagination:
  size: 5

#  main:
#    allow-circular-references: true