
server:
  port: 8099

spring:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jjang052
    password: 1234

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

    oauth2:
      client:
        registration:
          facebook:
            client-id: 315293796826930
            client-secret: 487af9479023b8c0e58f913b411327cf
            scope:
              - public_profile
              - email

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

file:
  path: C:/upload/
